version: '3'

volumes:
  grafana-data:

services:
  grafana:
    container_name: grafana_dashboard
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
