apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-clusterissuer
  namespace: cert-manager
spec:
  acme:
    email: <EMAIL>
    server:  https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-clusterissuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: traefik